services:
  - type: web
    name: senya-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://senya.onrender.com
      - key: MONGODB_DB_NAME
        value: senya
      - key: MONGODB_URI
        sync: false
